### ISSUE TITLE
Some Modifiers are missing!

### ISSUE THREAD

**Issue by Sirafy** [Dangry98/modifier_list-for-Blender-4.0#4] opened 2024-09-03 02:03 UTC
Hello, I love your addon and use it through the Blender Extensions website.
I'm using Blender 4.2.1 LTS, and I found that the old add modifier window is missing the "Smooth By Angle" modifier, I'm not sure if it is missing other modifiers.
Also, the old "Add Modifier" window is missing the new Blender category "Normals / Hair".
I tried to bypass these issues by using the new main "Add Modifier" window with the "Modifier List" addon but I didn't find an option to do that. "Please add this as an option"
I hope it's easy to fix issue, thank you for taking time reading this, and thank you for supporting Blender with your addons <3 
Best Regards...

**Comment by Dangry98** [comment] 2024-09-07 09:52
Hi @Sirafy, thanks for the report. This is not a bug, but missing features. 

Longterm I really whant to add it, but currently I am not sure how to do it, and if its even possible. In the meanwhile use the regluar deafult Shift A menu, and the new rightclick Shade Auto Smooth in Blender 4.2. The issue is that I do not whant to add all the new Geomtry Nodes Modifers manually, since it woud take too much time to do and maintain, I need to find a way to do it all automaticly whenever new stuff its added.

**Comment by Sirafy** [comment] 2024-09-07 16:07
Thanks for the reply, I got it.
My be if you add an option in the addon setting to use the new "Add Modifier" menu instead of the old one, this will allow the users to use the handy features of addon if they prefer the new menu.
I think this will fit wider range of users also.
Thank you again for supporting Blender users
Best regards...

**Comment by Dangry98** [comment] 2024-12-04 23:09
I added Auto Smooth and Edit Mesh to the leagacy menus:
![image](https://github.com/user-attachments/assets/25a1f0aa-ed6f-4e7d-b85c-171dc7e3321d)

**Comment by Dangry98** [comment] 2024-12-04 23:20
The new Modifier Menu is also aviable on Shift A, so all geonde modifiers can still be added. I am closing the issue. 

Hopfully in the futuer there will be a way to more easiley add the custom geo node modifers.

**Closed by Dangry98** 2024-12-04 23:20 UTC
